fonts = [
    "Arial",
    "Times New Roman",
    "Helvetica",
    "Courier New",
    "Georgia",
    "Verdana",
    "Comic Sans MS",
    "Palatino",
    "Tahoma",
    "Impact",
    "Garamond",
    "Book Antiqua",
    "Century Gothic",
    "Lucida Console",
    "Trebuchet MS",
    "Franklin Gothic Medium",
    "Copperplate",
    "Brush Script MT",
    "Consolas",
    "Monotype Corsiva",
    "Arial Narrow",
    "Cambria",
    "Didot",
    "Futura",
    "Baskerville",
    "Rockwell",
    "Helvetica Neue",
    "Candara",
    "Geneva",
    "Optima",
    "Bodoni MT",
    "Avant Garde",
    "Segoe UI",
    "Palatino Linotype",
    "Ebrima",
    "Calibri",
    "Century Schoolbook",
    "Leelawadee UI",
    "MS Gothic",
    "Segoe Print",
    "Eras ITC",
    "Engravers MT",
    "Constantia",
    "Perpetua",
    "Tw Cen MT",
    "Corbel",
    "Liberation Serif",
]
